# Generated by Django 3.2.12 on 2022-03-24 13:36

from django.db import migrations, models
import django.db.models.deletion
import upload_image.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_doctor_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=upload_image.models.scramble_uploaded_filename, verbose_name='Upload Image')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
    ]
